//
//  LoginInteractor.swift
//  DGSW-Petition_iOS
//
//  Created by 이영은 on 2021/04/19.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func doSomething(request: Login.Something.Request)
//    func doSomethingElse(request: Login.SomethingElse.Request)
}

protocol LoginDataStore {
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""

    // MARK: Do something (and send response to LoginPresenter)

    func doSomething(request: Login.Something.Request) {
        worker = LoginWorker()
//        worker?.doSomeWork()

        let response = Login.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: Login.SomethingElse.Request) {
//        worker = LoginWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Login.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
